package http

import (
    "bytes"
    "fmt"
    goHttp "net/http"
    "testing"
)

func TestGetRequestObject(t *testing.T) {
    type AutoGenerated struct {
        Errcode int    `json:"errcode"`
        Errmsg  string `json:"errmsg"`
    }

    request, _ := goHttp.NewRequest(
        "POST",
        `https://api.weixin.qq.com/sns/userinfo?access_token=16_Xtgu18-uW4r1zadDM_SCsGPEFprqijskkT1wjm8rNFIeg6De6xDsKrf8awGNANGbHzDQ0xtT0KkL6EImiPpwaw&lang=zh_CN&openid=akq2F0m-iDoEEeZJApDKW4Xu6vpU`,
        bytes.NewReader([]byte(`{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest, rid: 62e60704-26cd6c91-0e54aa65"}`)))

    a, err := GetRequestObject[AutoGenerated](request)
    fmt.Printf("code: %v msg: %v err: %v\n", a.Errcode, a.Errmsg, err)
}
